### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by yallop** [janestreet/ocaml_intrinsics#4]
At the moment some operations in this library crash with `SIGTRAP` or silently return wrong results on macOS ([test](https://github.com/yallop/intrinsics-report/blob/master/test.ml), [CI output](https://github.com/yallop/intrinsics-report/actions/runs/1972979049)).  This means that software built using this library will build and install on macOS systems, but fail catastrophically at run time.

Is it possible to have the library either fixed to work on macOS or marked in the metadata as Linux-only for the first OPAM release?

**Comment by hackedy** [comment]
Hi, I think this makes the core_unix v0.15 release impossible to install on MacOS. Is there a timeline for a fix or workaround? I think the only use of anything from ocaml_intrinsics over there is in the time stamp counter module: https://github.com/janestreet/core_unix/blob/a051098a918b950e9d0a5da7248f1bbfb51388e5/time_stamp_counter/src/time_stamp_counter.ml#L100

**Comment by gretay-js** [comment]
Sorry about the delay, I will get it fixed asap.
@yallop thank you for the detailed report and repo case! I think there is a bug (missing implementation) in the C stubs `int_stubs.c` when `__GNUC__` is not defined, although it should be defined when building with LLVM.

**Comment by gretay-js** [comment]
@yallop  I've updated your tests with the proposed fix and they [pass on the CI](https://github.com/gretay-js/intrinsics-report/tree/debug_macos). 

It took a fairly old mac to reproduce the failures locally for debugging purposes. All tests in this library pass on the old mac, except one floating point input (`float_stubs`compiles with a warning, so it's expected to have some precision difference and the module is not yet used in base/core). 

I would like to re-enable ocaml_intrinsics in opam for macos.

**Comment by yallop** [comment]
> @yallop I've updated your tests with the proposed fix and they [pass on the CI](https://github.com/gretay-js/intrinsics-report/tree/debug_macos).

That's good news.  Thank you for fixing this, @gretay-js

**Comment by barracuda156** [comment]
@yallop @gretay-js @hackedy Could anyone say what would it take to implement these for macOS on PowerPC? :)

**Comment by gretay-js** [comment]
@barracuda156 We would need to either find the corresponding instructions / C compiler intrinsics and provide (slower) software implementations for the missing ones. I don't have any way to test such an implementation, do you :)
