### ISSUE TITLE
Windows availability?

### ISSUE THREAD

**Issue by samwgoldman** [janestreet/ocaml_intrinsics#8]
The opam files [forbids installation on Windows](https://github.com/janestreet/ocaml_intrinsics/blob/a1ec71ecbaab4c376525bbe21307dda8d769188a/ocaml_intrinsics.opam#L22C2-L22C62), so it's not possible to install under Windows. This itself is not a problem, but because this library is a dependency of [Core_unix](https://github.com/janestreet/core_unix/blob/9832257b262eebbdf6d692508d4274ff3e52be01/core_unix.opam#L19) ([used here](https://github.com/janestreet/core_unix/blob/9832257b262eebbdf6d692508d4274ff3e52be01/time_stamp_counter/src/time_stamp_counter.ml#L101)), it's not possible to install Core_unix on Windows.

Is Core_unix comparable to the stdlib Unix module, which has ~defined behavior for Windows? If so, would it be possible to make Core_unix available to Windows users, either by lifting the restriction on this library or breaking the dependency between Core_unix and this library?

Thanks!

**Comment by gretay-js** [comment]
I am afraid we do not currently support `Core_unix` on Windows, and I am not sure it will build even if it didn't depend on `Ocaml_intrinsics`.

**Comment by samwgoldman** [comment]
Thanks for confirming. I think this means we will need to break our dependency on Core_unix. If you would be interested in eventually supporting Windows, I would be happy to help however I can.

Does non-support of Windows apply more broadly to JS open source projects?

**Comment by samwgoldman** [comment]
Following up as I work to break the dependency on Core_unix, a minor annoyance here is that `open Core` itself will shadow the `Sys` module, so that code using e.g. `Sys.readdir` will error with the "Use_Sys_unix" variant thing, and Sys_unix comes from Core_unix, so Core itself pseudo-depends on Core_unix.

**Comment by dkalinichenko-js** [comment]
Yeah, I think it would make sense.

@samwgoldman generally, we don't support Windows on our own, but we accept patches for Windows compatibility. So, if you send us a patch that makes `Core_unix` build on Windows (e. g., by not using the intrinsic and fixing other compatibility issues), we'll include it in the next release.
